### ISSUE TITLE
Review comments H1L021 PR # 46 - Python Script

### ISSUE THREAD

**Issue by Cyb3rPandaH** [OTRF/OSSEM-DM#48]
Comment in PR #46 @H1L021 
Regarding the python script. It is really cool :D I was thinking on doing something similar LOL. I just tested it and it works. Just a quick question: Would the script work when creating relationships in a year different than 2022?

**Comment by H1L021** [comment]
Actually, it won't and I put as a To-Do task at the end of my PR.
I will create a new PR to add current year instead of 2022

**Comment by Cyb3rPandaH** [comment]
Hi @H1L021 I just modified your PR with the update to the script.

I am basically working with a dictionary instead of a list.
The keys of the dictionary are the years, and the values of the dictionary are lists with the numbers used for the ID.

As we discussed before, I added this script to the ossemDM.py script so we can now add the ID to new yaml files after merging PR's. 🍻 

Even though your script is now part of the ossemDM.py script, please do not delete the updated generate_uuid. py script. 🙏 I will archive the script within the project later. We might need to use it in the future 👍 

I am closing this issue. Thank you again 🙌
